// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: raftx.proto

package raftxpb

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WitnessContext struct {
	Context                []byte   `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	LogTerm                uint64   `protobuf:"varint,2,opt,name=log_term,json=logTerm" json:"log_term"`
	LogSubterm             uint64   `protobuf:"varint,3,opt,name=log_subterm,json=logSubterm" json:"log_subterm"`
	ReplicationSet         []uint64 `protobuf:"varint,4,rep,name=replication_set,json=replicationSet" json:"replication_set,omitempty"`
	ReplicationSetOutgoing []uint64 `protobuf:"varint,5,rep,name=replication_set_outgoing,json=replicationSetOutgoing" json:"replication_set_outgoing,omitempty"`
	Votes                  []uint64 `protobuf:"varint,6,rep,name=votes" json:"votes,omitempty"`
}

func (m *WitnessContext) Reset()         { *m = WitnessContext{} }
func (m *WitnessContext) String() string { return proto.CompactTextString(m) }
func (*WitnessContext) ProtoMessage()    {}
func (*WitnessContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_00ef7fe27ad62c10, []int{0}
}
func (m *WitnessContext) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WitnessContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WitnessContext.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WitnessContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WitnessContext.Merge(m, src)
}
func (m *WitnessContext) XXX_Size() int {
	return m.Size()
}
func (m *WitnessContext) XXX_DiscardUnknown() {
	xxx_messageInfo_WitnessContext.DiscardUnknown(m)
}

var xxx_messageInfo_WitnessContext proto.InternalMessageInfo

type WitnessHardState struct {
	State                  HardState `protobuf:"bytes,1,opt,name=state" json:"state"`
	LastLogIndex           uint64    `protobuf:"varint,2,opt,name=last_log_index,json=lastLogIndex" json:"last_log_index"`
	LastLogTerm            uint64    `protobuf:"varint,3,opt,name=last_log_term,json=lastLogTerm" json:"last_log_term"`
	LastLogSubterm         uint64    `protobuf:"varint,4,opt,name=last_log_subterm,json=lastLogSubterm" json:"last_log_subterm"`
	Lead                   uint64    `protobuf:"varint,5,opt,name=lead" json:"lead"`
	ReplicationSet         []uint64  `protobuf:"varint,6,rep,name=replication_set,json=replicationSet" json:"replication_set,omitempty"`
	ReplicationSetOutgoing []uint64  `protobuf:"varint,7,rep,name=replication_set_outgoing,json=replicationSetOutgoing" json:"replication_set_outgoing,omitempty"`
}

func (m *WitnessHardState) Reset()         { *m = WitnessHardState{} }
func (m *WitnessHardState) String() string { return proto.CompactTextString(m) }
func (*WitnessHardState) ProtoMessage()    {}
func (*WitnessHardState) Descriptor() ([]byte, []int) {
	return fileDescriptor_00ef7fe27ad62c10, []int{1}
}
func (m *WitnessHardState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WitnessHardState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WitnessHardState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WitnessHardState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WitnessHardState.Merge(m, src)
}
func (m *WitnessHardState) XXX_Size() int {
	return m.Size()
}
func (m *WitnessHardState) XXX_DiscardUnknown() {
	xxx_messageInfo_WitnessHardState.DiscardUnknown(m)
}

var xxx_messageInfo_WitnessHardState proto.InternalMessageInfo

func init() {
	proto.RegisterType((*WitnessContext)(nil), "raftxpb.WitnessContext")
	proto.RegisterType((*WitnessHardState)(nil), "raftxpb.WitnessHardState")
}

func init() { proto.RegisterFile("raftx.proto", fileDescriptor_00ef7fe27ad62c10) }

var fileDescriptor_00ef7fe27ad62c10 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x86, 0x93, 0x36, 0x69, 0x2e, 0x27, 0xbd, 0xb9, 0xbd, 0x43, 0xb9, 0x0c, 0x5d, 0x4c, 0x4b,
	0xb9, 0x62, 0x10, 0x8c, 0xe0, 0xca, 0x75, 0xdd, 0x28, 0x08, 0x42, 0x2b, 0xb8, 0x0c, 0x69, 0x3b,
	0x0e, 0x81, 0x34, 0x13, 0x92, 0xa9, 0xf4, 0x31, 0x5c, 0xfa, 0x40, 0x2e, 0xba, 0xec, 0xd2, 0x95,
	0xd8, 0x66, 0xe9, 0x4b, 0xc8, 0x4c, 0xd2, 0x92, 0xaa, 0x08, 0xee, 0xce, 0x39, 0xff, 0x77, 0x16,
	0xff, 0x07, 0x76, 0x1a, 0xdc, 0x89, 0x85, 0x97, 0xa4, 0x5c, 0x70, 0x64, 0xa9, 0x25, 0x19, 0x77,
	0xda, 0x8c, 0x33, 0xae, 0x6e, 0x27, 0x72, 0x2a, 0xe2, 0x0e, 0xc8, 0xb8, 0x98, 0xfb, 0x6f, 0x3a,
	0x38, 0xb7, 0xa1, 0x88, 0x69, 0x96, 0x9d, 0xf3, 0x58, 0xd0, 0x85, 0x40, 0x18, 0xac, 0x49, 0x31,
	0x62, 0xbd, 0xa7, 0xbb, 0xcd, 0xe1, 0x76, 0x45, 0x5d, 0xf8, 0x15, 0x71, 0xe6, 0x0b, 0x9a, 0xce,
	0x70, 0xad, 0xa7, 0xbb, 0xc6, 0xc0, 0x58, 0xbe, 0x74, 0xb5, 0xa1, 0x15, 0x71, 0x76, 0x43, 0xd3,
	0x19, 0x3a, 0x00, 0x5b, 0x02, 0xd9, 0x7c, 0xac, 0x98, 0x7a, 0x85, 0x81, 0x88, 0xb3, 0x51, 0x71,
	0x47, 0x87, 0xf0, 0x27, 0xa5, 0x49, 0x14, 0x4e, 0x02, 0x11, 0xf2, 0xd8, 0xcf, 0xa8, 0xc0, 0x46,
	0xaf, 0xee, 0x1a, 0x43, 0xa7, 0x72, 0x1e, 0x51, 0x81, 0xce, 0x00, 0x7f, 0x00, 0x7d, 0x3e, 0x17,
	0x8c, 0x87, 0x31, 0xc3, 0xa6, 0xfa, 0xf8, 0xb7, 0xff, 0x71, 0x5d, 0xa6, 0xa8, 0x0d, 0xe6, 0x3d,
	0x17, 0x34, 0xc3, 0x0d, 0x85, 0x15, 0x4b, 0xff, 0xa9, 0x06, 0xad, 0xb2, 0xed, 0x45, 0x90, 0x4e,
	0x47, 0x22, 0x10, 0x14, 0x1d, 0x83, 0x99, 0xc9, 0x41, 0xb5, 0xb5, 0x4f, 0xff, 0x7a, 0x52, 0x4f,
	0x32, 0xf6, 0x76, 0x44, 0xd9, 0xa0, 0xa0, 0xd0, 0x11, 0x38, 0x51, 0x90, 0x09, 0x5f, 0x16, 0x0d,
	0xe3, 0x29, 0x5d, 0xec, 0xa9, 0x68, 0xca, 0xec, 0x8a, 0xb3, 0x4b, 0x99, 0x20, 0x17, 0x7e, 0xef,
	0xd8, 0x4f, 0x46, 0xec, 0x12, 0x55, 0xe6, 0x3c, 0x68, 0xed, 0xc8, 0xad, 0x3e, 0xa3, 0x02, 0x3b,
	0x25, 0xbc, 0x55, 0x88, 0xc1, 0x88, 0x68, 0x30, 0xc5, 0x66, 0x85, 0x51, 0x97, 0xaf, 0xe4, 0x36,
	0x7e, 0x2c, 0xd7, 0xfa, 0x4e, 0xee, 0xe0, 0xff, 0x72, 0x4d, 0xb4, 0xd5, 0x9a, 0x68, 0xcb, 0x0d,
	0xd1, 0x57, 0x1b, 0xa2, 0xbf, 0x6e, 0x88, 0xfe, 0x90, 0x13, 0xed, 0x31, 0x27, 0xda, 0x2a, 0x27,
	0xda, 0x73, 0x4e, 0xb4, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0xbd, 0xaf, 0x11, 0x93, 0x02,
	0x00, 0x00,
}

func (m *WitnessContext) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WitnessContext) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WitnessContext) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Votes) > 0 {
		for iNdEx := len(m.Votes) - 1; iNdEx >= 0; iNdEx-- {
			i = encodeVarintRaftx(dAtA, i, uint64(m.Votes[iNdEx]))
			i--
			dAtA[i] = 0x30
		}
	}
	if len(m.ReplicationSetOutgoing) > 0 {
		for iNdEx := len(m.ReplicationSetOutgoing) - 1; iNdEx >= 0; iNdEx-- {
			i = encodeVarintRaftx(dAtA, i, uint64(m.ReplicationSetOutgoing[iNdEx]))
			i--
			dAtA[i] = 0x28
		}
	}
	if len(m.ReplicationSet) > 0 {
		for iNdEx := len(m.ReplicationSet) - 1; iNdEx >= 0; iNdEx-- {
			i = encodeVarintRaftx(dAtA, i, uint64(m.ReplicationSet[iNdEx]))
			i--
			dAtA[i] = 0x20
		}
	}
	i = encodeVarintRaftx(dAtA, i, uint64(m.LogSubterm))
	i--
	dAtA[i] = 0x18
	i = encodeVarintRaftx(dAtA, i, uint64(m.LogTerm))
	i--
	dAtA[i] = 0x10
	if m.Context != nil {
		i -= len(m.Context)
		copy(dAtA[i:], m.Context)
		i = encodeVarintRaftx(dAtA, i, uint64(len(m.Context)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *WitnessHardState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WitnessHardState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WitnessHardState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ReplicationSetOutgoing) > 0 {
		for iNdEx := len(m.ReplicationSetOutgoing) - 1; iNdEx >= 0; iNdEx-- {
			i = encodeVarintRaftx(dAtA, i, uint64(m.ReplicationSetOutgoing[iNdEx]))
			i--
			dAtA[i] = 0x38
		}
	}
	if len(m.ReplicationSet) > 0 {
		for iNdEx := len(m.ReplicationSet) - 1; iNdEx >= 0; iNdEx-- {
			i = encodeVarintRaftx(dAtA, i, uint64(m.ReplicationSet[iNdEx]))
			i--
			dAtA[i] = 0x30
		}
	}
	i = encodeVarintRaftx(dAtA, i, uint64(m.Lead))
	i--
	dAtA[i] = 0x28
	i = encodeVarintRaftx(dAtA, i, uint64(m.LastLogSubterm))
	i--
	dAtA[i] = 0x20
	i = encodeVarintRaftx(dAtA, i, uint64(m.LastLogTerm))
	i--
	dAtA[i] = 0x18
	i = encodeVarintRaftx(dAtA, i, uint64(m.LastLogIndex))
	i--
	dAtA[i] = 0x10
	{
		size, err := m.State.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRaftx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintRaftx(dAtA []byte, offset int, v uint64) int {
	offset -= sovRaftx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *WitnessContext) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Context != nil {
		l = len(m.Context)
		n += 1 + l + sovRaftx(uint64(l))
	}
	n += 1 + sovRaftx(uint64(m.LogTerm))
	n += 1 + sovRaftx(uint64(m.LogSubterm))
	if len(m.ReplicationSet) > 0 {
		for _, e := range m.ReplicationSet {
			n += 1 + sovRaftx(uint64(e))
		}
	}
	if len(m.ReplicationSetOutgoing) > 0 {
		for _, e := range m.ReplicationSetOutgoing {
			n += 1 + sovRaftx(uint64(e))
		}
	}
	if len(m.Votes) > 0 {
		for _, e := range m.Votes {
			n += 1 + sovRaftx(uint64(e))
		}
	}
	return n
}

func (m *WitnessHardState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.State.Size()
	n += 1 + l + sovRaftx(uint64(l))
	n += 1 + sovRaftx(uint64(m.LastLogIndex))
	n += 1 + sovRaftx(uint64(m.LastLogTerm))
	n += 1 + sovRaftx(uint64(m.LastLogSubterm))
	n += 1 + sovRaftx(uint64(m.Lead))
	if len(m.ReplicationSet) > 0 {
		for _, e := range m.ReplicationSet {
			n += 1 + sovRaftx(uint64(e))
		}
	}
	if len(m.ReplicationSetOutgoing) > 0 {
		for _, e := range m.ReplicationSetOutgoing {
			n += 1 + sovRaftx(uint64(e))
		}
	}
	return n
}

func sovRaftx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRaftx(x uint64) (n int) {
	return sovRaftx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *WitnessContext) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRaftx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WitnessContext: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WitnessContext: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Context", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRaftx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRaftx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Context = append(m.Context[:0], dAtA[iNdEx:postIndex]...)
			if m.Context == nil {
				m.Context = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogTerm", wireType)
			}
			m.LogTerm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LogTerm |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogSubterm", wireType)
			}
			m.LogSubterm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LogSubterm |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRaftx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ReplicationSet = append(m.ReplicationSet, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRaftx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthRaftx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthRaftx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.ReplicationSet) == 0 {
					m.ReplicationSet = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRaftx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ReplicationSet = append(m.ReplicationSet, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplicationSet", wireType)
			}
		case 5:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRaftx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ReplicationSetOutgoing = append(m.ReplicationSetOutgoing, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRaftx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthRaftx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthRaftx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.ReplicationSetOutgoing) == 0 {
					m.ReplicationSetOutgoing = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRaftx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ReplicationSetOutgoing = append(m.ReplicationSetOutgoing, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplicationSetOutgoing", wireType)
			}
		case 6:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRaftx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Votes = append(m.Votes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRaftx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthRaftx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthRaftx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Votes) == 0 {
					m.Votes = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRaftx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Votes = append(m.Votes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Votes", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRaftx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRaftx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WitnessHardState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRaftx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WitnessHardState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WitnessHardState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRaftx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRaftx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.State.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastLogIndex", wireType)
			}
			m.LastLogIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastLogIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastLogTerm", wireType)
			}
			m.LastLogTerm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastLogTerm |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastLogSubterm", wireType)
			}
			m.LastLogSubterm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastLogSubterm |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lead", wireType)
			}
			m.Lead = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Lead |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRaftx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ReplicationSet = append(m.ReplicationSet, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRaftx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthRaftx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthRaftx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.ReplicationSet) == 0 {
					m.ReplicationSet = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRaftx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ReplicationSet = append(m.ReplicationSet, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplicationSet", wireType)
			}
		case 7:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRaftx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ReplicationSetOutgoing = append(m.ReplicationSetOutgoing, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRaftx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthRaftx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthRaftx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.ReplicationSetOutgoing) == 0 {
					m.ReplicationSetOutgoing = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRaftx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ReplicationSetOutgoing = append(m.ReplicationSetOutgoing, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplicationSetOutgoing", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRaftx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRaftx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRaftx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRaftx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRaftx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRaftx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRaftx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRaftx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRaftx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRaftx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRaftx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRaftx = fmt.Errorf("proto: unexpected end of group")
)
