syntax = "proto2";
package raftxpb;

import "gogoproto/gogo.proto";
import "raft.proto";

option (gogoproto.marshaler_all) = true;
option (gogoproto.sizer_all) = true;
option (gogoproto.unmarshaler_all) = true;
option (gogoproto.goproto_getters_all) = false;
option (gogoproto.goproto_enum_prefix_all) = false;
option (gogoproto.goproto_unkeyed_all) = false;
option (gogoproto.goproto_unrecognized_all) = false;
option (gogoproto.goproto_sizecache_all) = false;

message WitnessContext {
	optional bytes context = 1;
    optional uint64 log_term = 2 [(gogoproto.nullable) = false];
	optional uint64 log_subterm = 3 [(gogoproto.nullable) = false];
	repeated uint64 replication_set = 4;
	repeated uint64 replication_set_outgoing = 5;
	repeated uint64 votes = 6;
}

message WitnessHardState {
	optional raftpb.HardState state = 1 [(gogoproto.nullable) = false];
	optional uint64 last_log_term = 2 [(gogoproto.nullable) = false];
	optional uint64 last_log_subterm = 3 [(gogoproto.nullable) = false];
	repeated uint64 replication_set = 4;
	repeated uint64 replication_set_outgoing = 5;
}