syntax = "proto2";
package raftxpb;

import "gogoproto/gogo.proto";

option (gogoproto.marshaler_all) = true;
option (gogoproto.sizer_all) = true;
option (gogoproto.unmarshaler_all) = true;
option (gogoproto.goproto_getters_all) = false;
option (gogoproto.goproto_enum_prefix_all) = false;
option (gogoproto.goproto_unkeyed_all) = false;
option (gogoproto.goproto_unrecognized_all) = false;
option (gogoproto.goproto_sizecache_all) = false;

message WitnessContext {
	optional bytes context = 1;
	optional uint64 subterm = 2 [(gogoproto.nullable) = false];
	repeated uint64 replication_set = 3;
	repeated uint64 replication_set_outgoing = 4;
	repeated uint64 votes = 5;
}